### ISSUE TITLE
setup.pins not available in pre-compiled esp32/micropython/acep 

### ISSUE THREAD

**Issue by jjllddyy** [ondiiik/meteoink#1]
Unable to load from the precompiled /acep files (mpy 1.18):

`.. [main]                       Starting the application ...
!!! APPLICATION ERROR - REBOOTING !!!
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "app.py", line 4, in <module>
  File "jumpers.py", line 5, in <module>
ImportError: no module named 'setup.pins'`

full console output:
`rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4540
ho 0 tail 12 room 4
load:0x40078000,len:12344
ho 0 tail 12 room 4
load:0x40080400,len:4124
entry 0x40080680
Reading database ...
Loading module ulogging
.. [main]                       Starting the application ...
!!! APPLICATION ERROR - REBOOTING !!!
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "app.py", line 4, in <module>
  File "jumpers.py", line 5, in <module>
ImportError: no module named 'setup.pins'
ets Jun  8 2016 00:22:57`

**Comment by ondiiik** [comment]
Unfortunately I'm unable to reproduce the issue. Module `setup.pins` is present in `acep` variant [here](https://github.com/ondiiik/meteoink/blob/master/esp32/micropython/acep/setup/pins.py) and works fine to me. Is this module present in your ESP32 file system?
